[package]
name = "glOS"
version = "0.1.0"
edition = "2024"
authors = ["GLStudios <58615717+GamingLiamStudios@users.noreply.github.com>"]
license = "GPL-2.0-only"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
acpi = "6.0"
raw-cpuid = "11.6"
x86_64 = "0.15"
pci_types = "0.10"

spin = "0.10"
embedded-graphics = { version = "0.8", features = ["fixed_point"] }
bytemuck = "1.24"
num-traits = { version = "0.2", default-features = false }

[lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"
perf = "deny"
all = "deny"
